[package]
name = "rust-x"
version = "0.1.0"
edition = "2021"

[dependencies]
ashpd = { version = "0.8.1", features = ["gtk4"] }
async-channel = "2.3.1"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }
